### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by Poolj2023** [SheLuvDx/PrimeStealer#1]
Bro, pude compilarlo, anda perfecto, pero a los 20 dias Discord me deshabilita la cuenta.. Hay alguna manera para que discord no me deshabilite la cuenta? se podra hacer que los registros vayan a Telegram?

**Comment by Poolj2023** [comment]
Bro, I was able to compile it, it works perfectly, but after 20 days Discord disables my account. Is there a way so that Discord doesn't disable my account? Could the records go to Telegram?

**Comment by SheLuvDx** [comment]
I Have Fixed That Have Fun
