### ISSUE TITLE
"pyinstaller" is not an internal or external command, executable program, or batch file.

### ISSUE THREAD

**Issue by dayzfake** [SheLuvDx/PrimeStealer#2]
Hi bro, I have one problem, as soon as I choose to build an exe, and write y after that, "pyinstaller" writes to me is not an internal or external command, executable program, or batch file. You don't know how to solve it.? 

Image https://imgur.com/a/gdEZSea

**Comment by SheLuvDx** [comment]
I Have fix that have fun
