### ISSUE TITLE
holy skid

### ISSUE THREAD

**Issue by Azuuu1** [SheLuvDx/PrimeStealer#8]
No talent. just skidding crazy how u got 30 stars for skidwork

**Comment by MrShadowDev** [comment]
> > > No talent. just skidding crazy how u got 30 stars for skidwork
> > 
> > 
> > from who he skidded i want to see original src
> 
> original creal stealer i dont think its up since when it got down a wave of skids happend

any stable fork from it? even if its not updated

**Comment by Azuuu1** [comment]
> > > > No talent. just skidding crazy how u got 30 stars for skidwork
> > > 
> > > 
> > > from who he skidded i want to see original src
> > 
> > 
> > original creal stealer i dont think its up since when it got down a wave of skids happend
> 
> any stable fork from it? even if its not updated

u can just try to search it up ig but idk
